//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Ride { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public string SpecialNeeds { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public System.DateTime ChangedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
