//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideInfo
    {
        public int Id { get; set; }
        public string RideName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public System.DateTime ChangedOn { get; set; }
    }
}
